use_frameworks!

target 'PushLib_Example', :exclusive => true do
  pod 'PushLib', :path => '../'
end

target 'PushLib_Tests', :exclusive => true do
  pod 'PushLib', :path => '../'

  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  pod 'OCMapper', '2.1'
  pod 'AFNetworking', '2.5.0'

end
