use_frameworks!

pod 'OCMapper', '2.1'
pod 'AFNetworking', '2.6.3'
pod 'PushLib', :path => '../'

target 'PushLib_Example', :exclusive => true do

end

target 'PushLib_Tests', :exclusive => true do
  pod 'Specta'
  pod 'FBSnapshotTestCase'


end