use_frameworks!

pod 'OCMapper', '2.1'
pod 'AFNetworking', '2.6.3'

target 'PushLib_Example', :exclusive => true do
  pod 'PushLib', :path => '../'
end

target 'PushLib_Tests', :exclusive => true do
  pod 'PushLib', :path => '../'

  
end
